function output_path = create_sepia_header(json_path, output_path)
%CREATE_SEPIA_HEADER Creates a SEPIA MATLAB header from GUI JSON metadata.
%
% output_path = CREATE_SEPIA_HEADER(json_path)
% output_path = CREATE_SEPIA_HEADER(json_path, output_path)
%
% json_path may point to either:
%   1. <participant>_sepia_header.json, containing the acquisition fields; or
%   2. <participant>_qsm_project.json, containing a "sepia_header" path.
%
% The JSON header is generated by qsm_pp_gui. Echo times must already be in
% seconds, central frequency in Hz, B0 in tesla, and voxel size in mm.
% The resulting MAT file contains the variable names expected by SEPIA:
% B0, CF, B0_dir, TE, matrixSize, and voxelSize.

    arguments
        json_path (1, 1) string
        output_path (1, 1) string = ""
    end

    if ~isfile(json_path)
        error('qsm_pp_gui:HeaderJsonNotFound', ...
            'JSON input file does not exist: %s', json_path);
    end

    try
        metadata = jsondecode(fileread(json_path));
    catch exception
        error('qsm_pp_gui:InvalidHeaderJson', ...
            'Could not read JSON input %s: %s', json_path, exception.message);
    end

    % A project JSON points to the actual SEPIA header JSON. Resolve that
    % indirection so callers may conveniently pass either file.
    if isfield(metadata, 'sepia_header') && ~isfield(metadata, 'TE')
        header_json_path = string(metadata.sepia_header);
        if ~isfile(header_json_path)
            error('qsm_pp_gui:HeaderJsonNotFound', ...
                'Project JSON refers to a missing SEPIA header: %s', ...
                header_json_path);
        end
        try
            metadata = jsondecode(fileread(header_json_path));
        catch exception
            error('qsm_pp_gui:InvalidHeaderJson', ...
                'Could not read referenced header %s: %s', ...
                header_json_path, exception.message);
        end
        source_header_path = header_json_path;
    else
        source_header_path = json_path;
    end

    required_fields = {'B0', 'CF', 'B0_dir', 'TE', ...
                       'matrix_size', 'voxel_size'};
    for index = 1:numel(required_fields)
        field_name = required_fields{index};
        if ~isfield(metadata, field_name)
            error('qsm_pp_gui:MissingHeaderField', ...
                'Required field "%s" is missing from %s.', ...
                field_name, source_header_path);
        end
    end

    B0 = double(metadata.B0);
    CF = double(metadata.CF);
    TE = double(metadata.TE(:).');
    B0_dir = double(metadata.B0_dir(:));
    matrixSize = double(metadata.matrix_size(:).');
    voxelSize = double(metadata.voxel_size(:).');

    validateattributes(B0, {'double'}, {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, 'B0');
    validateattributes(CF, {'double'}, {'scalar', 'real', 'finite', 'positive'}, ...
        mfilename, 'CF');
    validateattributes(TE, {'double'}, {'vector', 'real', 'finite', 'positive', 'increasing'}, ...
        mfilename, 'TE');
    validateattributes(B0_dir, {'double'}, {'vector', 'numel', 3, 'real', 'finite'}, ...
        mfilename, 'B0_dir');
    if ~any(B0_dir)
        error('qsm_pp_gui:InvalidB0Direction', ...
            'B0_dir cannot be the zero vector.');
    end
    validateattributes(matrixSize, {'double'}, ...
        {'vector', 'numel', 3, 'real', 'finite', 'positive', 'integer'}, ...
        mfilename, 'matrixSize');
    validateattributes(voxelSize, {'double'}, ...
        {'vector', 'numel', 3, 'real', 'finite', 'positive'}, ...
        mfilename, 'voxelSize');

    if output_path == ""
        [source_directory, source_name, ~] = fileparts(source_header_path);
        source_name = erase(source_name, "_sepia_header");
        output_path = fullfile(source_directory, source_name + "_sepia_header.mat");
    end

    output_directory = fileparts(output_path);
    if output_directory ~= "" && ~isfolder(output_directory)
        mkdir(output_directory);
    end

    save(output_path, 'B0', 'CF', 'B0_dir', 'TE', ...
        'matrixSize', 'voxelSize');

    fprintf('SEPIA header created: %s\n', output_path);
end
